export default {
    LOGIN_USER :'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    SIGNUP_USER: 'SIGNUP_USER',
    LOGOUT_USER :'LOGOUT_USER',
    GET_USER_JOINED_CHANNELS_SUCCESS :'GET_USER_JOINED_CHANNELS_SUCCESS',
    CHANNEL_SELECTED: 'CHANNEL_SELECTED',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS'
}