export default {
    LOGIN_USER :'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    SIGNUP_USER: 'SIGNUP_USER',
    LOGOUT_USER :'LOGOUT_USER'
}